version: "3.7"

services:
  db:
    container_name: codexkeycloakdb
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:z

  codex-keycloak:
    container_name: codexkeycloak
    image: codexkeycloak:latest
    restart: unless-stopped
    build: .
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    depends_on:
      - db

volumes:
  db: