version: "3.7"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - "db:/var/lib/postgresql/data"

  keycloak:
    image: keycloak/keycloak:21.0
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://db:5432/${DB_NAME}"
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./init/feasibility-realm.json:/opt/keycloak/data/import/realm.json:ro
    depends_on:
      - db

volumes:
  db:
