version: "3.7"

services:
  codex-keycloak:
    container_name: codexkeycloak
    image: codexkeycloak:${TAG}
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - codex-develop
    ports:
      - 8080:8080

networks:
  codex-develop:
    external: true
    name: codex-develop